version: '3'

services:
  deploy:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=$ENVIRONMENT
    restart: always
    ports:
      - '127.0.0.1:${PORT_FRONTEND}:4000'
